use_frameworks!

platform :ios, '8.0'

target 'MediaUI_Example' do
  pod 'MediaUI', :path => '../'
  pod 'BATabBarController', :path => 'ThirdParty'
  pod 'Masonry'
  
  #pod 'Masonry'
  pod 'ReactiveCocoa','~>2.5'
  pod 'MJRefresh'
  pod 'MBProgressHUD'
  pod 'MJExtension'
  pod 'AFNetworking'
  pod 'FMDB'
  pod 'SDWebImage'
  pod 'SDWebImage/WebP'
  pod 'YYWebImage'
  pod 'YYImage/WebP'
  pod 'Reachability'
  pod 'GPUImage'
  pod 'Bugly'
  
  target 'MediaUI_Tests' do
    inherit! :search_paths

    
  end
end
